### ISSUE TITLE
Server close connection if we don't change UA

### ISSUE THREAD

**Issue by kotori2** [TechCiel/jlu-health-reporter#1]
~~just too lazy to send a pr~~

**Comment by TechCiel** [comment]
// 我这边没观测到啊？

**Comment by TechCiel** [comment]
观测到了未知原因的连接中断，但是行为比较随机，暂时还不好做定论

**Comment by fichas** [comment]
> 观测到了未知原因的连接中断，但是行为比较随机，暂时还不好做定论

我这边观测到是凌晨左右可能由于学校服务器造成的访问中断

**Comment by kotori2** [comment]
@fichas 看起来是的，服务器每小时会重启，等重启完就没问题了。改ua能好我也不知道为啥，可能是玄学

**Comment by TechCiel** [comment]
毕竟是个临时用用的脚本，就大重试间隔外加大重试次数解决吧，还能顺带提供一点时间上的 randomness （大雾

**Comment by fichas** [comment]
理论上可以每隔三小时用一次

（大雾

**Comment by fichas** [comment]
我刚分析完他那个doAction post的东西 我就在Github找到你写的了😂
话说他post里的那个rand 你分析了嘛
