### ISSUE TITLE
党史学习对应的配置文件项

### ISSUE THREAD

**Issue by lonble** [TechCiel/jlu-health-reporter#10]
21年4月8日在打卡页面加入了党史学习，如果不修改配置文件会导致打卡失败。
仅需在配置文件的`fields`对象中加入`fieldDJXXyc`属性，设置其值为1。当前的`fields`对象如下：
```json
"fields": {
    "fieldZtw": "1",
    "fieldDJXXyc": "1"
}
```

**Comment by LadyBugLC** [comment]
确实,我刚刚也发现了

**Comment by TechCiel** [comment]
建议所有正在运行本科自动打卡的同学更新配置文件！
