### ISSUE TITLE
我就知道不止我一个人想到要做这个

### ISSUE THREAD

**Issue by Evyde** [TechCiel/jlu-health-reporter#3]
大佬是真厉害，[我是拿Selenium（Google Chrome Driver）搞的](https://github.com/ForeverOpp/JLU-HealthForm-AutoFiller)，效率上差多了而且还容易出错，大佬这个直接抓包真的厉害，学习了学习了。
如果能搞一个队列填报，程序自动判断每天是否填报完成，记录填报内容就更好了。

**Comment by TechCiel** [comment]
过奖了，反正本来也就是做来自己用的东西...
填报完成这个估计不好判断，因为这个东西是一个 transaction ，拆协议的时候没看到个人有相关接口可用。
至于记录填报内容，因为涉及 privacy 其实不怎么好，如果需要可以打开 debug ，匹配一下程序输出。

**Comment by Evyde** [comment]
好，看来抓协议是真的难顶，那Chrome Driver这个事情就比较简单了
