### ISSUE TITLE
能更新一下代码用于新的每日三打卡一签到吗？

### ISSUE THREAD

**Issue by qsbird** [TechCiel/jlu-health-reporter#4]
如题
打卡不及时会受处分
哭唧唧

**Comment by TechCiel** [comment]
考试周巨大忙...感觉很可能不会有时间更

而且这个不同于假期无意义的统计，涉及测量数据和确认位置，感觉做脚本的话风险更大一些

应该不会随便处分吧...多半是导员吓唬人，先订个闹钟吧

**Comment by fichas** [comment]
目前没法进界面 不清楚具体什么情况 要是跟原来一样的实现方式的话 那就是改第9行就好。要是不是的话 那可能就比较搞了

**Comment by Evyde** [comment]
用selenium就可以，体温的话，如果是正常是不需要填具体温度的，应该比较好实现。这个玩意实在是烦，这一两天就是不复习也要搞出来。

**Comment by fichas** [comment]
> 用selenium就可以，体温的话，如果是正常是不需要填具体温度的，应该比较好实现。这个玩意实在是烦，这一两天就是不复习也要搞出来。

不用把 直接把传回来的值 修改一下传回去就行。
    "fieldZtw": "",//早
    "fieldZtwyc": "",
    "fieldZhongtw": "",//中
    "fieldZhongtwyc": "",
    "fieldWantw": "",//晚
    "fieldWantwyc": "",

**Comment by TechCiel** [comment]
各位佬都很强呀，感谢各位的支持和关注。

看起来工作量没那么大，晚上抓个包看下，做的话会开新 branch 。

**Comment by Waveleting** [comment]
大佬方不方便写一个浴室自动预约的脚本啊

**Comment by fichas** [comment]
那个不是f12 p一下图就行了 （而且他也不咋查）




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Waveleting"<notifications@github.com&gt;; 
发送时间: 2020年8月10日(星期一) 下午3:10
收件人: "TechCiel/jlu-health-reporter"<jlu-health-reporter@noreply.github.com&gt;; 
抄送: "杨浩宇"<454831537@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [TechCiel/jlu-health-reporter] 能更新一下代码用于新的每日三打卡一签到吗？ (#4)





 
大佬方不方便写一个浴室自动预约的脚本啊

**Comment by TechCiel** [comment]
@Waveleting 你要的是不是 https://github.com/TechCiel/jlu-yuci ？咋还把回复删了

**Comment by Evyde** [comment]
> 各位佬都很强呀，感谢各位的支持和关注。
> 
> 看起来工作量没那么大，晚上抓个包看下，做的话会开新 branch 。

这个限制时间打开，不知道是前台还是后台实现的，所以今天可能不行。

**Comment by Evyde** [comment]
话说这个往issue上面贴标签怎么搞

**Comment by fichas** [comment]
> > 各位佬都很强呀，感谢各位的支持和关注。
> > 看起来工作量没那么大，晚上抓个包看下，做的话会开新 branch 。
> 
> 这个限制时间打开，不知道是前台还是后台实现的，所以今天可能不行。

后台实现的
回传的时候就没有数据（

**Comment by Evyde** [comment]
> > > 各位佬都很强呀，感谢各位的支持和关注。
> > > 看起来工作量没那么大，晚上抓个包看下，做的话会开新 branch 。
> > 
> > 
> > 这个限制时间打开，不知道是前台还是后台实现的，所以今天可能不行。
> 
> 后台实现的
> 回传的时候就没有数据（

那无了，只能明天抓包了。

**Comment by fichas** [comment]
目前处于测试版 我fork了一版 有需要的自取把（出事概不负责）

**Comment by TechCiel** [comment]
> 目前处于测试版 我fork了一版 有需要的自取把（出事概不负责）

我昨晚已经推了 3plus1 分支并且部署测试了，今天中午看起来正常，今晚点名没问题就可以上线力。

**Comment by fichas** [comment]
我把你的分支改了一下（ 你的crontab太鬼畜了

**Comment by TechCiel** [comment]
目前观测到的结果来看，校区、宿舍楼、寝室号三项似乎系统不会自动给，晚上再观测一次看看。如果这个没有的话会很麻烦，因为最终用户不见得会获取这几个参数的系统内 id ，考虑做个生成器。


> 我把你的分支改了一下（ 你的crontab太鬼畜了

这个，，，忘记了 crontab 有这种语法，下个版本补上。

**Comment by fichas** [comment]
> 目前观测到的结果来看，校区、宿舍楼、寝室号三项似乎系统不会自动给，晚上再观测一次看看。如果这个没有的话会很麻烦，因为最终用户不见得会获取这几个参数的系统内 id ，考虑做个生成器。
> 
> > 我把你的分支改了一下（ 你的crontab太鬼畜了
> 
> 这个，，，忘记了 crontab 有这种语法，下个版本补上。

早上的没给 中午的我手动补了一下 给出来了（

**Comment by fichas** [comment]
明天早上看一下（要是没有的话 就搞一个

**Comment by Evyde** [comment]
> 目前观测到的结果来看，校区、宿舍楼、寝室号三项似乎系统不会自动给，晚上再观测一次看看。如果这个没有的话会很麻烦，因为最终用户不见得会获取这几个参数的系统内 id ，考虑做个生成器。
> 
> > 我把你的分支改了一下（ 你的crontab太鬼畜了
> 
> 这个，，，忘记了 crontab 有这种语法，下个版本补上。

不仅没给，提交的时候还有xq_Name、gyl_Name这种东西，难顶。

**Comment by TechCiel** [comment]
啊，头痛，这样多用户会变得很复杂...

**Comment by fichas** [comment]
> > 目前观测到的结果来看，校区、宿舍楼、寝室号三项似乎系统不会自动给，晚上再观测一次看看。如果这个没有的话会很麻烦，因为最终用户不见得会获取这几个参数的系统内 id ，考虑做个生成器。
> > > 我把你的分支改了一下（ 你的crontab太鬼畜了
> > 
> > 
> > 这个，，，忘记了 crontab 有这种语法，下个版本补上。
> 
> 不仅没给，提交的时候还有xq_Name、gyl_Name这种东西，难顶。

中午手动补了一下都有了（

**Comment by fichas** [comment]
xq=校区

**Comment by fichas** [comment]
gyl=公寓楼

**Comment by Evyde** [comment]
> gyl=公寓楼

我看明白了，我fork的代码里面加了这些，但是可能没加全。

**Comment by Evyde** [comment]
> 啊，头痛，这样多用户会变得很复杂...

还可以吧，创建一个列表让用户填校区、公寓名字就行，你看我fork的你的代码的多用户实现。

**Comment by TechCiel** [comment]
这五个参数如果绑定到用户配置里，那个 tuple 会巨大臃肿。你们觉得是前端填好执行一个 JS 获取参数，还是自己填报一次然后运行程序获取参数，这两个哪个友好一些？

**Comment by fichas** [comment]
> 这五个参数如果绑定到用户配置里，那个 tuple 会巨大臃肿。你们觉得是前端填好执行一个 JS 获取参数，还是自己填报一次然后运行程序获取参数，这两个哪个友好一些？

很简单 抓取他上一次填写的表单就行(

**Comment by Evyde** [comment]
> 这五个参数如果绑定到用户配置里，那个 tuple 会巨大臃肿。你们觉得是前端填好执行一个 JS 获取参数，还是自己填报一次然后运行程序获取参数，这两个哪个友好一些？

自己填报一次获得参数太麻烦了，还得抓包。不如让用户配置一个json文件，每次读取就行了。

**Comment by Evyde** [comment]
> > 这五个参数如果绑定到用户配置里，那个 tuple 会巨大臃肿。你们觉得是前端填好执行一个 JS 获取参数，还是自己填报一次然后运行程序获取参数，这两个哪个友好一些？
> 
> 很简单 抓取他上一次填写的表单就行(

表单似乎不会自动保存

**Comment by fichas** [comment]
我指的是通过已经填报过的表单来读
![image](https://user-images.githubusercontent.com/16914302/89861297-00240180-dbd8-11ea-8ce9-7a167570118a.png)

**Comment by TechCiel** [comment]
@fichas 有无 Telegram ？版聊伤神

**Comment by fichas** [comment]
> @fichas 有无 Telegram ？版聊伤神

我是群友（

**Comment by Evyde** [comment]
> 我指的是通过已经填报过的表单来读
> ![image](https://user-images.githubusercontent.com/16914302/89861297-00240180-dbd8-11ea-8ce9-7a167570118a.png)

确实不错，但是用户多了可能不如直接填配置文件容易，因为得多次登录。
你看我这个：
![image](https://user-images.githubusercontent.com/9302540/89861387-40837f80-dbd8-11ea-8b53-630e260a900d.png)

**Comment by Evyde** [comment]
> > @fichas 有无 Telegram ？版聊伤神
> 
> 我是群友（

大佬们果然非同凡响，都有群，能拉我这个蒟蒻进群么？

**Comment by TechCiel** [comment]
> > @fichas 有无 Telegram ？版聊伤神
> 
> 我是群友（

求 PM 下，没认出来

**Comment by TechCiel** [comment]
推了更新，如果不跑爆就是最终版本了

**Comment by TechCiel** [comment]
顺便打广告 https://t.me/JLULUG

**Comment by TechCiel** [comment]
新版本经过测试已经推送到 master ，如有 bug 请另开 issue 。
